Stashed
Anna-Pinewood/Ischemic_Stroke_Prediction pull request #5
Opened 2023-02-10 18:53 UTC by Martinumer

2023-02-12 08:36 UTC, Anna-Pinewood requested changes

2023-02-12 08:36 UTC, Anna-Pinewood commented on scenarios/futher_training.py
> +    model.hparams.learning_rate = lr_finder.suggestion()
ты, кстати, уверена, что он передаётся в модель? чтоб убедиться, можно подебажить и посмотреть learning_rate параметр внутри модели, из простого - можно его print-анунть в тестовом обучении. Если коротко, хочется док-в, что модель его реально использует

2023-02-12 08:41 UTC, Martinumer commented on scenarios/futher_training.py
> +    model.learning_rate
Какая из: 88?

2023-02-12 11:12 UTC, Martinumer commented on scenarios/futher_training.py
> +    model.learning_rate
Убрала 88 сроку, она и правда лишняя

2023-02-12 12:03 UTC, Anna-Pinewood commented on scenarios/futher_training.py
> +    model.learning_rate
комментарий всегда относится к последней строчке ( в данном случае 88), гитзаб просто добавляет предыдущее для полноты картины.

2023-02-12 17:46 UTC, Anna-Pinewood commented on scenarios/futher_training.py
> +    logger.info('lr_finder.suggestion: ', str(model.learning_rate))
Если человек не запускал тюнер, он всё равно увидит в логах `lr_finder.suggestion`, что не есть правда, перепиши, пожалуйста эту строчку.

2023-02-13 07:25 UTC, Anna-Pinewood approved these changes

2023-02-13 16:25 UTC, merged